model_type: 0
model_name: GraphDRP

marker: GAT_GCN_number2

cuda_name: cuda:0

# work_dir: GAT_GCN
work_dir: text_num_GDSCv2_dis
batch_size: 
  train: 256 
  val: 256
  test: 256 
lr: 0.001
num_epoch: 100
log_interval: 50
seed: 171

dataset_name: GDSCv2

dataset_type: 
  scale: 1
  select_type: m2r
  # r3  three datasets are all random, and not mixed
  # m2r train and val datasets are mixed, test dataset is random
  # dataset_path: /home/lk/project/NCI60_dataset/normal_format
  # dataset_path: /home/lk/project/NCI60_dataset/selected
  dataset_path: /home/lk/project/MSDA/data/process/GDSC2_dataset/drug_classed
  train: 0.7
  val: 0.2
  test: 0.1

    

model:
  
  drug_module: 
    module_name: 
      - GATConv
      - GCNConv
    input_drug_feature_dim: 90
    output_drug_feature_dim: 128
    layer_num: 2

    gnn_layers: 
      - 
        intput: 90
        output: 90
        dropout: 0.0
        feature_pre_dropout: 0
        heads: 10
      - 
        intput: 900
        output: 900
        dropout: 0.0
        feature_pre_dropout: 0
        

    linear_layers:
      - 
        operate_name: linear
        param:
          - 1800
          - 1500
      - 
        operate_name: relu
      - 
        operate_name: dropout
        param: 0.5
      - 
        operate_name: linear
        param:
          - 1500
          - 128

      # - 
      #   operate_name: linear
      #   param:
      #     - 1800
      #     - 1500
      # - 
      #   operate_name: relu
      # - 
      #   operate_name: dropout
      #   param: 0.2

    graph_pooling: max_mean
    dropout: 0.5

  cell_module: 
    module_name: Conv1d
    input_cell_feature_dim: 735
    output_cell_feature_dim: 128
    fc_1_dim: 128
    layer_num: 3
    layer_hyperparameter:
      kernel_size:
        - 8
        - 8
        - 8
      maxpool1d: 
        - 3
        - 3 
        - 3
      cnn_channels:
        - 32
        - 64
        - 128


  fusion_module:
    fc_1_dim: 1024
    fc_2_dim: 128
    fc_3_dim: 1
    dropout: 0.5
    fusion_mode: concat
